name: Build Docker Image

on:
  push:
    tags:
      - 'v*.*'  # Trigger on version tags (e.g., v1.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          docker build -t ghcr.io/sspt/devcontainer-for-cf-workers:${VERSION} -t ghcr.io/sspt/devcontainer-for-cf-workers:latest .